### ISSUE TITLE
Conversion from string to Integer not valid bei leerer TextBox

### ISSUE THREAD

**Issue by GhostGCR** [JMacherius/Das-kleine-Ein-mal-Eins#1]
Hi Jan,

wenn die Textbox 1 leer ist, versucht VB dennoch, den Input in einen Integer umzuwandeln. Das führt zu einem kleinen Anwendungsfehler mit Fehlermeldung. Ein Convert.ToInt32(Eingabe) in einer Try-Catch Anweisung sollte das ganze beheben :)

Gruß,
Jonas

**Comment by JMacherius** [comment]
Hi Jonas,

danke für Deinen Hinweis, Du hast natürlich recht. Ich muss aber auch sagen: Das habe ich gestern in paar Minuten zusammen geschrieben damit meine Tochter erstmal was zum üben in Mathe hat. Andererseits habe ich mir endlich mal VisualStudio 2022 heruntergeladen und wollte nur bisschen basteln, auch was die Integration von GitHub betrifft.

Also: Die Ausnahme wird jetzt abgefangen ;-) Dir eine schöne Zeit,

Gruß Jan.
